image: php:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: testing
  MYSQL_ROOT_PASSWORD: password

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update -yqq

  - apt-get install git libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libonig-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libzip-dev -yqq

  - docker-php-ext-install mbstring pdo_mysql curl intl gd xml zip bz2 opcache

  - pecl install xdebug
  - docker-php-ext-enable xdebug

  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --ignore-platform-reqs

  - cp .env.testing .env
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate
  - php artisan passport:install
  - php artisan love:reaction-type-add --default

test:
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
